services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vpn_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    image: php:apache
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql